name: Refresh live.json

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Refresh live.json
        run: npm run update:live
      - name: Commit updated live.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/live.json
          git commit -m "chore: refresh live.json @ $(date -u +"%Y-%m-%d %H:%M UTC")" || echo "No changes"
          git push
